version: '3.5'
services:
  dbclient:
    image: alpine
    environment:
      - BACKUP_ENABLED=1
      - BACKUP_INTERVAL=3600
      - BACKUP_PATH=/data
      - BACKUP_FILENAME=db_backup
    networks:
      - db
    entrypoint: |
      sh -c 'apk add --no-cache mysql-client && \
        while true; do \
          if [ "$BACKUP_ENABLED" == "1" ]; then \
            sleep "$BACKUP_INTERVAL"; \
            mkdir -p "$BACKUP_PATH/$(date +%F)"; \
            echo "$(date +%FT%H.%M) - Making Backup to : $BACKUP_PATH/$(date +%F)/$BACKUP_FILENAME-$(date +%FT%H.%M).sql.gz"; \
            mysqldump -u mydbuser -pmydbpass -h dblb --all-databases | gzip > "$BACKUP_PATH/$(date +%F)/$BACKUP_FILENAME-$(date +%FT%H.%M).sql.gz"; \
            find "$BACKUP_PATH" -mtime +7 -delete; \
          fi; \
        done'
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1

  dbcluster:
    image: toughiq/mariadb-cluster
    networks:
      - db
    expose:
      - "3306"
    environment:
      - DB_SERVICE_NAME=dbcluster
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mydbuser
      - MYSQL_PASSWORD=mydbpass
    deploy:
      placement:
        constraints:
          - node.labels.app == web
      mode: replicated
      replicas: 1

  dblb:
    image: toughiq/maxscale
    networks:
      - db
    ports:
      - 3306:3306
    environment:
      - DB_SERVICE_NAME=dbcluster
      - ENABLE_ROOT_USER=1
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=211.183.3.99
      device: ":/volume/db"

networks:
  db:
    external: true
